### ISSUE TITLE
What part in GitHub workflows builds the actual DACPAC to deploy?

### ISSUE THREAD

**Issue by juantarquino-ssb** [Azure-Samples/serverless-full-stack-apps-azure-sql#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
> What part in GitHub workflows builds the actual DACPAC to deploy? I saw a github workflow for deploying the Dacpac but not one for building the dacpac from sources.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yorek** [comment]
You can find the script to build the .dacpac in the `database/scripts` folder. Building the .dacpac is not part of the workflow. Ideally you make the changes to your database offline, on your dev machine, then you generate the .dacpac and push it into the repo so that it can be deployed.
